# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/pythonProjects/tubitak-fuzzy/design/design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 600)
        MainWindow.setStyleSheet("#MainWindow{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridFrame = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridFrame.sizePolicy().hasHeightForWidth())
        self.gridFrame.setSizePolicy(sizePolicy)
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout.addWidget(self.gridFrame)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rule_button = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rule_button.sizePolicy().hasHeightForWidth())
        self.rule_button.setSizePolicy(sizePolicy)
        self.rule_button.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.rule_button.setStyleSheet("#pushButton_4:active{\n"
"\n"
"}")
        self.rule_button.setObjectName("rule_button")
        self.verticalLayout_3.addWidget(self.rule_button)
        self.startButton = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setStyleSheet("")
        self.startButton.setObjectName("startButton")
        self.verticalLayout_3.addWidget(self.startButton)
        self.horizontalLayout.addWidget(self.frame_4)
        self.output_frame = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_frame.sizePolicy().hasHeightForWidth())
        self.output_frame.setSizePolicy(sizePolicy)
        self.output_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.output_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output_frame.setObjectName("output_frame")
        self.output_layout = QtWidgets.QVBoxLayout(self.output_frame)
        self.output_layout.setContentsMargins(-1, 50, -1, 50)
        self.output_layout.setObjectName("output_layout")
        self.horizontalLayout.addWidget(self.output_frame)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalFrame_2 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_2.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_2.setSizePolicy(sizePolicy)
        self.horizontalFrame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.horizontalFrame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.and_method_box = QtWidgets.QComboBox(self.horizontalFrame_2)
        self.and_method_box.setObjectName("and_method_box")
        self.gridLayout_3.addWidget(self.and_method_box, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.horizontalFrame_2)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.or_method_box = QtWidgets.QComboBox(self.horizontalFrame_2)
        self.or_method_box.setObjectName("or_method_box")
        self.gridLayout_3.addWidget(self.or_method_box, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.defuz_box = QtWidgets.QComboBox(self.horizontalFrame_2)
        self.defuz_box.setObjectName("defuz_box")
        self.gridLayout_3.addWidget(self.defuz_box, 2, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.horizontalFrame_2)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.variable_name_line = QtWidgets.QLineEdit(self.frame_5)
        self.variable_name_line.setObjectName("variable_name_line")
        self.gridLayout_2.addWidget(self.variable_name_line, 1, 1, 1, 1)
        self.range_label = QtWidgets.QLabel(self.frame_5)
        self.range_label.setObjectName("range_label")
        self.gridLayout_2.addWidget(self.range_label, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.variable_type_line = QtWidgets.QLabel(self.frame_5)
        self.variable_type_line.setObjectName("variable_type_line")
        self.gridLayout_2.addWidget(self.variable_type_line, 2, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 21))
        self.menubar.setObjectName("menubar")
        self.menuEDit = QtWidgets.QMenu(self.menubar)
        self.menuEDit.setObjectName("menuEDit")
        self.menuNew_Fuzzy_System = QtWidgets.QMenu(self.menuEDit)
        self.menuNew_Fuzzy_System.setObjectName("menuNew_Fuzzy_System")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAdd_Variable_2 = QtWidgets.QMenu(self.menuEdit)
        self.menuAdd_Variable_2.setObjectName("menuAdd_Variable_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOutput_2 = QtWidgets.QAction(MainWindow)
        self.actionOutput_2.setObjectName("actionOutput_2")
        self.actionInput_2 = QtWidgets.QAction(MainWindow)
        self.actionInput_2.setObjectName("actionInput_2")
        self.actiontest = QtWidgets.QAction(MainWindow)
        self.actiontest.setObjectName("actiontest")
        self.actionLanguage = QtWidgets.QAction(MainWindow)
        self.actionLanguage.setObjectName("actionLanguage")
        self.actionImport_Data = QtWidgets.QAction(MainWindow)
        self.actionImport_Data.setObjectName("actionImport_Data")
        self.actionSave_Data = QtWidgets.QAction(MainWindow)
        self.actionSave_Data.setObjectName("actionSave_Data")
        self.actionInput = QtWidgets.QAction(MainWindow)
        self.actionInput.setObjectName("actionInput")
        self.actionOutput = QtWidgets.QAction(MainWindow)
        self.actionOutput.setObjectName("actionOutput")
        self.actionMamdani = QtWidgets.QAction(MainWindow)
        self.actionMamdani.setObjectName("actionMamdani")
        self.actionSugeno = QtWidgets.QAction(MainWindow)
        self.actionSugeno.setObjectName("actionSugeno")
        self.menuNew_Fuzzy_System.addAction(self.actionMamdani)
        self.menuNew_Fuzzy_System.addAction(self.actionSugeno)
        self.menuEDit.addAction(self.menuNew_Fuzzy_System.menuAction())
        self.menuEDit.addAction(self.actionLanguage)
        self.menuEDit.addAction(self.actionImport_Data)
        self.menuEDit.addAction(self.actionSave_Data)
        self.menuAdd_Variable_2.addAction(self.actionInput)
        self.menuAdd_Variable_2.addAction(self.actionOutput)
        self.menuEdit.addAction(self.menuAdd_Variable_2.menuAction())
        self.menubar.addAction(self.menuEDit.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rule_button.setText(_translate("MainWindow", "Mamdani"))
        self.startButton.setText(_translate("MainWindow", "Görüntüle"))
        self.label.setText(_translate("MainWindow", "And metodu"))
        self.label_2.setText(_translate("MainWindow", "Or metodu"))
        self.label_3.setText(_translate("MainWindow", "Defuzification"))
        self.range_label.setText(_translate("MainWindow", "[0 , 1]"))
        self.label_7.setText(_translate("MainWindow", "Aralık"))
        self.label_6.setText(_translate("MainWindow", "Tip"))
        self.label_4.setText(_translate("MainWindow", "Seçili Değişken"))
        self.label_5.setText(_translate("MainWindow", "İsim"))
        self.variable_type_line.setText(_translate("MainWindow", "input"))
        self.menuEDit.setTitle(_translate("MainWindow", "Dosya"))
        self.menuNew_Fuzzy_System.setTitle(_translate("MainWindow", "New Fuzzy System"))
        self.menuEdit.setTitle(_translate("MainWindow", "Düzenleme"))
        self.menuAdd_Variable_2.setTitle(_translate("MainWindow", "Değişken Ekle"))
        self.actionOutput_2.setText(_translate("MainWindow", "Output"))
        self.actionInput_2.setText(_translate("MainWindow", "Input"))
        self.actiontest.setText(_translate("MainWindow", "test"))
        self.actionLanguage.setText(_translate("MainWindow", "Dil"))
        self.actionImport_Data.setText(_translate("MainWindow", "Veriyi yükle"))
        self.actionSave_Data.setText(_translate("MainWindow", "Veriyi kaydet"))
        self.actionInput.setText(_translate("MainWindow", "Input"))
        self.actionOutput.setText(_translate("MainWindow", "Output"))
        self.actionMamdani.setText(_translate("MainWindow", "Mamdani"))
        self.actionSugeno.setText(_translate("MainWindow", "Sugeno"))

