# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/pythonProjects/tubitak-fuzzy/design/input.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(824, 611)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalFrame = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.variable_info_frame = QtWidgets.QFrame(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.variable_info_frame.sizePolicy().hasHeightForWidth())
        self.variable_info_frame.setSizePolicy(sizePolicy)
        self.variable_info_frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.variable_info_frame.setObjectName("variable_info_frame")
        self.variable_info_layout = QtWidgets.QHBoxLayout(self.variable_info_frame)
        self.variable_info_layout.setObjectName("variable_info_layout")
        self.verticalFrame1 = QtWidgets.QFrame(self.variable_info_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame1.sizePolicy().hasHeightForWidth())
        self.verticalFrame1.setSizePolicy(sizePolicy)
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.var_name = QtWidgets.QLineEdit(self.verticalFrame1)
        self.var_name.setObjectName("var_name")
        self.verticalLayout_2.addWidget(self.var_name)
        self.variable_info_layout.addWidget(self.verticalFrame1)
        self.verticalFrame_2 = QtWidgets.QFrame(self.variable_info_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame_2.sizePolicy().hasHeightForWidth())
        self.verticalFrame_2.setSizePolicy(sizePolicy)
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.verticalFrame_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.domain_min = QtWidgets.QLineEdit(self.verticalFrame_2)
        self.domain_min.setObjectName("domain_min")
        self.horizontalLayout_2.addWidget(self.domain_min)
        self.domain_max = QtWidgets.QLineEdit(self.verticalFrame_2)
        self.domain_max.setObjectName("domain_max")
        self.horizontalLayout_2.addWidget(self.domain_max)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.set_domain = QtWidgets.QPushButton(self.verticalFrame_2)
        self.set_domain.setObjectName("set_domain")
        self.verticalLayout_4.addWidget(self.set_domain)
        self.variable_info_layout.addWidget(self.verticalFrame_2)
        self.verticalGroupBox_3 = QtWidgets.QGroupBox(self.variable_info_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalGroupBox_3.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox_3.setSizePolicy(sizePolicy)
        self.verticalGroupBox_3.setObjectName("verticalGroupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalGroupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.triangular_mf = QtWidgets.QRadioButton(self.verticalGroupBox_3)
        self.triangular_mf.setCheckable(True)
        self.triangular_mf.setObjectName("triangular_mf")
        self.verticalLayout_5.addWidget(self.triangular_mf)
        self.gaussian_mf = QtWidgets.QRadioButton(self.verticalGroupBox_3)
        self.gaussian_mf.setObjectName("gaussian_mf")
        self.verticalLayout_5.addWidget(self.gaussian_mf)
        self.trapezoidal_mf = QtWidgets.QRadioButton(self.verticalGroupBox_3)
        self.trapezoidal_mf.setObjectName("trapezoidal_mf")
        self.verticalLayout_5.addWidget(self.trapezoidal_mf)
        self.variable_info_layout.addWidget(self.verticalGroupBox_3)
        self.verticalLayout.addWidget(self.variable_info_frame)
        self.term_frame = QtWidgets.QFrame(self.verticalFrame)
        self.term_frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.term_frame.setObjectName("term_frame")
        self.term_layout = QtWidgets.QVBoxLayout(self.term_frame)
        self.term_layout.setObjectName("term_layout")
        self.verticalFrame2 = QtWidgets.QFrame(self.term_frame)
        self.verticalFrame2.setObjectName("verticalFrame2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame2)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.edit_frame = QtWidgets.QFrame(self.verticalFrame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_frame.sizePolicy().hasHeightForWidth())
        self.edit_frame.setSizePolicy(sizePolicy)
        self.edit_frame.setObjectName("edit_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.edit_frame)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.edit_frame_2 = QtWidgets.QFrame(self.edit_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_frame_2.sizePolicy().hasHeightForWidth())
        self.edit_frame_2.setSizePolicy(sizePolicy)
        self.edit_frame_2.setObjectName("edit_frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.edit_frame_2)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.edit_frame_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.horizontalFrame = QtWidgets.QFrame(self.edit_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mf_label = QtWidgets.QLineEdit(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mf_label.sizePolicy().hasHeightForWidth())
        self.mf_label.setSizePolicy(sizePolicy)
        self.mf_label.setObjectName("mf_label")
        self.horizontalLayout_4.addWidget(self.mf_label)
        self.mf_add_button = QtWidgets.QPushButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mf_add_button.sizePolicy().hasHeightForWidth())
        self.mf_add_button.setSizePolicy(sizePolicy)
        self.mf_add_button.setObjectName("mf_add_button")
        self.horizontalLayout_4.addWidget(self.mf_add_button)
        self.verticalLayout_6.addWidget(self.horizontalFrame)
        self.mf_values = QtWidgets.QFrame(self.edit_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mf_values.sizePolicy().hasHeightForWidth())
        self.mf_values.setSizePolicy(sizePolicy)
        self.mf_values.setObjectName("mf_values")
        self.mf_values_layout = QtWidgets.QHBoxLayout(self.mf_values)
        self.mf_values_layout.setContentsMargins(2, 2, 2, 2)
        self.mf_values_layout.setSpacing(3)
        self.mf_values_layout.setObjectName("mf_values_layout")
        self.verticalLayout_6.addWidget(self.mf_values)
        self.horizontalLayout_3.addWidget(self.edit_frame_2)
        self.info_label = QtWidgets.QLabel(self.edit_frame)
        self.info_label.setText("")
        self.info_label.setObjectName("info_label")
        self.horizontalLayout_3.addWidget(self.info_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.edit_frame)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.graph_frame = QtWidgets.QFrame(self.verticalFrame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_frame.sizePolicy().hasHeightForWidth())
        self.graph_frame.setSizePolicy(sizePolicy)
        self.graph_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.graph_frame.setObjectName("graph_frame")
        self.graph_layout = QtWidgets.QVBoxLayout(self.graph_frame)
        self.graph_layout.setContentsMargins(5, 5, 5, 5)
        self.graph_layout.setSpacing(4)
        self.graph_layout.setObjectName("graph_layout")
        self.horizontalLayout_5.addWidget(self.graph_frame)
        self.verticalFrame3 = QtWidgets.QFrame(self.verticalFrame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame3.sizePolicy().hasHeightForWidth())
        self.verticalFrame3.setSizePolicy(sizePolicy)
        self.verticalFrame3.setMinimumSize(QtCore.QSize(150, 50))
        self.verticalFrame3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.verticalFrame3.setObjectName("verticalFrame3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalFrame3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.mf_function_list = QtWidgets.QListWidget(self.verticalFrame3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mf_function_list.sizePolicy().hasHeightForWidth())
        self.mf_function_list.setSizePolicy(sizePolicy)
        self.mf_function_list.setObjectName("mf_function_list")
        self.verticalLayout_7.addWidget(self.mf_function_list)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.update_mf_button = QtWidgets.QPushButton(self.verticalFrame3)
        self.update_mf_button.setObjectName("update_mf_button")
        self.horizontalLayout_6.addWidget(self.update_mf_button)
        self.remove_mf_button = QtWidgets.QPushButton(self.verticalFrame3)
        self.remove_mf_button.setObjectName("remove_mf_button")
        self.horizontalLayout_6.addWidget(self.remove_mf_button)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5.addWidget(self.verticalFrame3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.setStretch(0, 1)
        self.term_layout.addWidget(self.verticalFrame2)
        self.verticalLayout.addWidget(self.term_frame)
        self.horizontalLayout.addWidget(self.verticalFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 824, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.label_2.setText(_translate("MainWindow", "Range"))
        self.set_domain.setText(_translate("MainWindow", "Set Range"))
        self.verticalGroupBox_3.setTitle(_translate("MainWindow", "Functions"))
        self.triangular_mf.setText(_translate("MainWindow", "Triangular"))
        self.gaussian_mf.setText(_translate("MainWindow", "Gaussian"))
        self.trapezoidal_mf.setText(_translate("MainWindow", "Trapezoidal"))
        self.label_3.setText(_translate("MainWindow", "Label"))
        self.mf_add_button.setText(_translate("MainWindow", "Add"))
        self.update_mf_button.setText(_translate("MainWindow", "Update"))
        self.remove_mf_button.setText(_translate("MainWindow", "Remove"))

